[package]
name = "spin-componentize"
version = "0.1.0"

edition = "2021"

[dependencies]
anyhow = "1.0.69"
wasmparser = "0.102.0"
wasm-encoder = "0.25.0"
# TODO: PR changes upstream so we can point to a release here:
wit-component = { git = "https://github.com/dicej/wasm-tools", branch = "cabi-post" }

[dev-dependencies]
anyhow = "1.0.69"
wasmtime = { version = "7.0.0", features = ["component-model"] }
tokio = { version = "1", features = ["macros", "rt", "fs"] }
spin-abi-conformance = { path = "abi-conformance" }
