[package]
name = "spin-abi-conformance"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
async-trait = "0.1.66"
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", features = [
    "component-model",
], rev = "3878a0025e8c2f44f8ed2e7064cd5188574e7d6c" }
wasmtime-wasi = { git = "https://github.com/bytecodealliance/wasmtime", rev = "3878a0025e8c2f44f8ed2e7064cd5188574e7d6c", feature = [
    "tokio",
] }
cap-std = "2.0.0"
tokio = { version = "1", features = ["macros", "rt", "fs", "rt-multi-thread"] }
clap = { version = "3.1.15", features = ["derive", "env"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_core = "0.6.3"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.3.0"
toml = "0.5.9"
serde_json = "1.0"
